import * as screen from './screen';
export {screen};
import * as color from './color';
export {color};
import * as fetch from './fetch';
export {fetch};
import * as time from './time';
export {time};
import * as dishnow from './dishnow';
export {dishnow};
import * as phone from './phone';
export {phone};
// export {default as phone} from './phone';
